import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {NavBar, Portafolio, Contact, HeroBanner, Skills} from '../components'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
   
          <style>
          @import url('https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Tiro+Devanagari+Marathi:ital@0;1&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Yeseva+One&display=swap');

          </style>
      </Head>
      <NavBar/>
      <HeroBanner/>
      <Portafolio/>
      <Skills/>
      <Contact/>
    </div>
  )
}

export default Home
